### ISSUE TITLE
Mounting Issue w/ Camera SD over USB

### ISSUE THREAD

**Issue by kzaremski** [ShekelsBot/RockStat2020_Bruckbauer#16]
Camera is not showing up in `lsblk` even when turned on and USB port power on, most likely an electrical/hardware issue with the cable.

**Enhancement:** The camera SD should be mounted at runtime and not at boot time. UUID of camera can be automatically extracted from lsblk & blkid.

**Comment by AMVdude** [comment]
Cass and I just bought two new cables today and are testing them.

**Comment by kzaremski** [comment]
Issue was fixed with a new cable.
Camera is now mounted at runtime, code was a part of the unified control file rewrite.
