### ISSUE TITLE
Mounting Issues - Input/output errors

### ISSUE THREAD

**Issue by a-bauer-eng** [ShekelsBot/RockStat2020_Bruckbauer#22]
```
mount: /mnt/usb: special device /dev/sda1 does not exist.
cp: cannot stat '/mnt/usb/DCIM/*/*AB.MP4': Input/output error
```

While using control in the master branch encountered the error

Used manualcamctl to verify the issue - the USB port is good.

I believe the Device name is changing once power is shut off and turned on to the USB port
Recommend using device ID instead of name.

<img width="545" alt="Screen Shot 2021-05-21 at 1 31 05 PM" src="https://user-images.githubusercontent.com/49802191/119189272-17cac900-ba39-11eb-95da-e054c246a987.png">

**Comment by kzaremski** [comment]
Device name is still sda1, this is probably due to an electrical issue. Use
the test cable to verify.

**Comment by a-bauer-eng** [comment]
I was able to get it to mount manually using the cut up cable. I was not able to get it to mount with the script using the cut cable.
Couldn't verify with another test cable as I didn't want to take apart the camera case to get at the usb plug.
